config/routes.rb
Rails.application.routes.draw do
  root "top#index"
  get "about" => "top#about", as: "about"
  get "forbeginner" => "top#forbeginner", as: "forbeginner"
  get "admin" => "admin#top", as: "admin"
  get "treasure" => "searches#treasure", as: "treasure"
  get "exit" => "searches#exit", as: "exit"
  get "error" => "share#error", as: "error"

  #get "lesson/:action(/:name)" => "lesson"
  resources :users do
    collection { get "search" }
  end
  resources :articles
  resources :songs
  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :search
end

app/views/shared/_errors.html.erb
<% logger.progname = "views/shared" %>
<% if obj.errors.present? %>
<div id="errors">
<% logger.error "ERROR発生" %>
<h3>Error!</h3>
<ul>
  <% obj.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
  <% end %>
</ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%= link_to "What about this site", :about %> |
Copyright (C) Yu Tamura
2017-2019

app/views/shared/_header.html.erb
<h1> 特別研究用サイト </h1>

<% if current_user %>
<p class="user">
<%= link_to current_user.user_name + "さん", :account %> |
<%= link_to "logout", :session,
  method: :delete, data: { confirm: "Are you sure you want to logout?" } %>
</p>
<% end %>

<div class="menubar">
<%= menu_link_to "TOP", root_path %>
  &nbsp; | &nbsp; <%= menu_link_to "Announcement", :articles %>
  <% if current_user %>
  &nbsp; | &nbsp; <%= menu_link_to "For Beginner", :forbeginner %>
  &nbsp; | &nbsp; <%= menu_link_to "My Page", :account %>
  &nbsp; | &nbsp; <%= menu_link_to "Search", :search %>
  <% end %>
  <% if admin_user == 1 %>
  &nbsp; | &nbsp; <%= menu_link_to "Admin Only", :admin %>
  &nbsp; | &nbsp; <%= menu_link_to "Other & Test Page", "#" %>
  <% end %>
</div>

app/views/shared/_login_form.html.erb
<h2>Login</h2>
<% if flash.alert %><p class="alert"><%= flash.alert %></p><% end %>
<%= form_tag :session do %>
<table id="login_form">
  <tr>
    <td style="text-align: right">User Name:</td>
    <td><%= text_field_tag "user_name", "", style: "width: 120px" %></td>
  </tr>
  <tr>
    <td style="text-align: right">Password:</td>
    <td><%= password_field_tag "password", "", style: "width: 120px" %></td>
  </tr>
  <tr>
    <td colspan="2" style="text-align: center">
    <%= submit_tag "Login" %></td>
  </tr>
</table>
<% end %>

app/views/shared/_sidebar.html.erb
<%= render "shared/login_form" unless current_user %>

<h2>Recent Announcement</h2>
<ul>
  <% Article.sidebar_articles(current_user, 5).each do |article| %>
    <li><%= link_to article.title, article %></li>
  <% end %>
</ul>

<h2>Recent Search songs</h2>
<% if current_user then%>
<% @user = User.find(current_user.id) %>
  <ul>
    <% @song = Song.find_by(id: @user.recent1) %>
    <li><%= @song != nil ? (link_to @song.song_title, song_path(@user.recent1)) : "削除されました" %></li>

    <% @song = Song.find_by(id: @user.recent2) %>
    <li><%= @song != nil ? (link_to @song.song_title, song_path(@user.recent2)) : "削除されました" %></li>

    <% @song = Song.find_by(id: @user.recent3) %>
    <li><%= @song != nil ? (link_to @song.song_title, song_path(@user.recent3)) : "削除されました" %></li>

    <% @song = Song.find_by(id: @user.recent4) %>
    <li><%= @song != nil ? (link_to @song.song_title, song_path(@user.recent4)) : "削除されました" %></li>

    <% @song = Song.find_by(id: @user.recent5) %>
    <li><%= @song != nil ? (link_to @song.song_title, song_path(@user.recent5)) : "削除されました" %></li>

  </ul>
<% elsif %>
  ログインしてください!<br>
<% end %>